export const FETCH_NEWS = "FETCH_NEWS";
export const FETCH_NEWS_FAILED = "FETCH_NEWS_FAILED";
export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";
export const LOADING_BEGIN = "LOADING_BEGIN";
export const LOADING_COMPLETE = "LOADING_COMPLETE";
export const FETCH_STOCK = "FETCH_STOCK";
export const FETCH_STOCK_FAILED = "FETCH_STOCK_FAILED";
export const FETCH_STOCK_SUCCESS = "FETCH_STOCK_SUCCESS";
